spring.application.name=tfg_backend

# Configuración de conexión a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/Lunaris
spring.datasource.username=postgres
spring.datasource.password=1234

# Configuración de JPA / Hibernate
# "update": Actualiza el esquema si cambias tus modelos (Entities), crea tablas si no existen.
spring.jpa.hibernate.ddl-auto=update

# Mostrar las consultas SQL en la consola (útil para desarrollo/debug)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Dialecto de PostgreSQL (Spring suele detectarlo solo, pero es bueno definirlo)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT settings
jwt.secret=gfdfgfwqrvsedacxzasdfghytr23456789
jwt.expiration-ms=3600000

# Email settings (Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=inesgarcham@gmail.com
spring.mail.password=pzjl jszw hlem oxpo
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Frontend URL (para enlaces de recuperación)
app.frontend.url=http://localhost:4200